// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/14/2026, 10:58:16 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/muhless/Coding/pg_pritani/front_end/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/muhless/Coding/pg_pritani/front_end/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/muhless/Coding/pg_pritani/front_end/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/muhless/Coding/pg_pritani/front_end/app/plugins/**/*.{js,ts,mjs}","/home/muhless/Coding/pg_pritani/front_end/app/composables/**/*.{js,ts,mjs}","/home/muhless/Coding/pg_pritani/front_end/app/utils/**/*.{js,ts,mjs}","/home/muhless/Coding/pg_pritani/front_end/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/muhless/Coding/pg_pritani/front_end/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/muhless/Coding/pg_pritani/front_end/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/muhless/Coding/pg_pritani/front_end/app/app.config.{js,ts,mjs}","/home/muhless/Coding/pg_pritani/front_end/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;